### PR TITLE
WIP: Fix 48

### PR DESCRIPTION
**Pull request by marcvs**
Addresses #48 : 

Handle matching in case value is not a list.

Yet, the test fails, even though only one email of two email addresses needs to match

### CODE REVIEW

**Comment by marcvs** [comment]
@lburgey: Before I remove all references to OneOf, I thought you'd better have a say on this ;)

**Comment by lburgey** [comment]
> @lburgey: Before I remove all references to OneOf, I thought you'd better have a say on this ;)

I think you can remove it, so go ahead

**Comment by dianagudu** [comment]
I'd suggest to keep OneOf and simply subclass from N_Of with `n=1`. Not just because I use it in `motley_cue` :), but I'd imagine it's a common use case, and then it's just nice to have a shorthand.

**Comment by marcvs** [comment]
ok

**Pull request merged**
